databases:
  - name: firstproject_db
    databaseName: firstproject
    user: firstproject

services:
  - type: web
    name: firstproject
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: PORT
        value: 3000
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: firstproject_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false 